# Generated by Django 5.0.2 on 2024-03-14 13:36

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('role', models.CharField(choices=[('customer', 'customer'), ('driver', 'driver')], max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=5)),
                ('is_authorized', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='user_accounts', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='user_accounts', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'Pending acceptance'), ('1', 'Courier in route to pickup location'), ('2', 'Courier in route to destination'), ('3', 'Completed'), ('4', 'Cancelled')], default='0', max_length=100)),
                ('duration', models.DurationField()),
                ('is_payed', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='peyk.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='peyk.account')),
            ],
        ),
    ]
